### ISSUE TITLE
Create service wrapping Any23 so that Validata can use it

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/BMUSE#1]
Idea is use our service such that validata can simply call our service and get the parsed RDF, which it will then process

**Comment by kcmcleod** [comment]
Might be worth trying this with node if I cant find a suitable RDF extractor...
https://www.npmjs.com/package/microdata-node

**Comment by kcmcleod** [comment]
have a demo... not great tho

https://lxbisel.macs.hw.ac.uk:8080/scraper/getRDF?url=https://ega-archive.org/

**Comment by AlasdairGray** [comment]
Validata has been made to work with the BMUSE webapp.
