### ISSUE TITLE
Opportunities for linking

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/BMUSE#18]
@ id provides the IRI for the current node. It means blank nodes are no longer blank.

However, if used in a sub-part of the json-ld (e.g., for an Organization or Funder etc) it provides the IRI for the sub-part. Any23 will use this IRI instead of a blank node for the sub-part, e.g.,
```
...	{
            "@type" : "Dataset",
            "name" : "Protein Structural Domain Boundaries",
            ...
            "citation": {
                  "@id": "http://www.identifiers.org/pubmed/27899584",
                  "@type": "ScholarlyArticle",
                  ...
            }, ...
	},
```
becomes:
```
<http://bioschemas.org/crawl/v1/1/www.cathdb.info/2057404480> <http://schema.org/citation> <http://www.identifiers.org/pubmed/27899584> .
<http://www.identifiers.org/pubmed/27899584> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/ScholarlyArticle> .
```
These @ ids should provide a way to link documents together.

**Comment by kcmcleod** [comment]
Notice that while the GSDT tool keeps the @ id property, Any23 removes it: https://search.google.com/structured-data/testing-tool#url=www.cathdb.info

**Comment by AlasdairGray** [comment]
Linking between properties is now covered in the Bioschemas tutorials
