### ISSUE TITLE
Using sitemap for crawling ?!

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/BMUSE#23]
Eg, https://www.ebi.ac.uk/biosamples/sitemap

Problem is many sites dont provide a sitemap, eg, https://www.ebi.ac.uk/chembl/sitemap

**Comment by AlasdairGray** [comment]
Should we be encouraging the use of sitemap as best practice within Bioschemas. This could be particularly beneficial for dynamically generated sites.

**Comment by kcmcleod** [comment]
A sitemap would be very helpful for crawling; however, it will provide no help for scraping (which is the current problem we have with *some* generated sites).

**Comment by AlasdairGray** [comment]
An idea that we had previously discussed in Bioschemas was using the sitemap to point to a dump of all the Bioschemas markup.

**Comment by petrospaps** [comment]
This is already part of the functionality of BMUSE
