### ISSUE TITLE
@ id causes more problems

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/BMUSE#24]
@ id is problem when it is missing as we have lots of blank nodes see #4 
@ id is problem when Biosamples use the same value for every DataRecord see #22 

ALSO @ id is problem with MINT as they assign both the DataCatalog and the nested Dataset the same @ id value; hence both Google & our scraper treat it as the same concept with unexpected results: [see GSDTT]{https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fmint.bio.uniroma2.it}
* Dataset is nested within DataCatalog, but the properties have been combined into a single concept which is both a DataCatalog & Dataset. 
    * **note** my tool does not do this. Instead all properties are assigned to the DataCatalog and the Dataset just has a url.
* As DataCatalog and Dataset both have a description the combined concept has 2 descriptions with the same values (they are not merged together because the DataCatalog description has an extra period, thus they are not identical).
    * They also both have the keywords, but this time the lists are truly identical so just 1 keywords property exists

**Comment by kcmcleod** [comment]
@AlasdairGray - nothing we can really do about this apart from improve training?!

**Comment by AlasdairGray** [comment]
Improve training. Provide a proper validation tool. Inform people when we come across issues like this.

**Comment by AlasdairGray** [comment]
`@id` property is now a minimal property in all profiles. Training has been added about this
