### ISSUE TITLE
Virtuoso doesn't reliably load files

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/BMUSE#25]
I produced 19973 nq files, each containing a different graph. Yet only 14799 graphs exist in Virtuoso.

Running through the graphs in the repo (using JAVA) I see that 5176 graphs are missing.

Looking at Virtuoso, it claims these files were loaded successfully so that is obviously worthless.

**Comment by AlasdairGray** [comment]
service has been deprecated, so this is no longer an issue
