### ISSUE TITLE
New server; potential number of triples

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/BMUSE#34]
ArrayExpress = 2453383
* 72284 experiments
* 2,381,099 assays

Biosamples = 10,770,874 pages.

CATH = 147739340
* 52,073,853 protein seq
* 95,665,487 predicted domains

Chebi = 111404
* 55998 compounds (checked)
* 55406 (unchecked)

Chembl = 3,012,600 pages.
* 1.9 million compounds 
* 1.1 million assays
* 127k other pages 

EGA = 1910
* 1910 studies

ENA = 339525938034
* 261,149,873 sequences
* 339,264,788,161 nucleotides

EnsemblGenome

HPA:
* 26,000 antibodies
* 17,000 genes

Interpro = 36872 entries.

Orphanet
* 5856 diseases
* 3573 genes

PDBE
* 154478 PDB
* 8770 EMDB

PRIDE:
* 8085 datasets

Silva = don't understand stats page

String
* 9,643,763 proteins
* 2,031 organisms

UniProt = 168321807
560,537 SwissProt
167,761,270 Trembl

**Comment by kcmcleod** [comment]
Chembl + Biosamples = 13783474 pages.

Assume 20 triples per page, thus 275,669,480 triples.

[10 bytes per quad](https://www.mail-archive.com/virtuoso-users@lists.sourceforge.net/msg06875.html) so 2,756,694,800 bytes therefore 2.75GB of RAM required to store the quads... more will be needed to manipulate, but haven't found a page for that.

[Each instance needs at least 64MB & another 130KB per database connection](http://docs.openlinksw.com/virtuoso/srvadmopreq/).

CentOS needs at least 1GB for the OS, so let us give it 2. 

In total 6GB should be enough RAM for everything.

**Comment by AlasdairGray** [comment]
Not sure I follow the RAM calculation. My instinct is that we want as much RAM as possible. 

In Open PHACTS our first test server had 96GB RAM and our eventual dev server had over 300GB.

I'm not suggesting that we go to this extreme, but we certainly want more than 16GB

**Comment by kcmcleod** [comment]
> but we certainly want more than 16GB
I'm not sure where 16GB came from as the calculations suggested we could use just 6GB for our current dataset. Once crawled (which will take a couple of months) I intend to test if this is correct.

I'm currently using a 16GB machine, and it is fine if you run nothing else. However, as soon as you do it is not.

>  My instinct is that we want as much RAM as possible.
Yes and no. The more memory the better BUT it may be more useful to have 2 big machines rather than 1 huge machine. At the minute I'm having to do everything on lxbisel because none of the other machines are big enough. Therefore I have a single machine operating as both dev and production. If you don't need a production service not a problem, but if you want reliable consumption that is not acceptable.

> In Open PHACTS our first test server had 96GB RAM 
Did you use the enterprise version of Virtuoso? The OS version only seems to support up to 64GB RAM; at least there are no config settings for anything beyond that.
