### ISSUE TITLE
Selenium chrome driver processes do not seem to be killed

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/BMUSE#42]
[This](https://artoftesting.com/automationTesting/difference-between-driver-close-and-driver-quit-command-in-selenium-webdriver.html) discusses the difference between close() and quit() in Selenium.

quit() should kill everything; however, it seems to leave several processes running.

Googling has revealed this a common issue at different times; mostly for Windows. Sometimes it is fixed by a Windows update. Other times people recommend calling close(), then wait() before calling quit(). Some recommend using the 'no-sandbox' argument, others say to remove it. None of these work for me on the mac.

I am reduced to running a terminal command to kill the processes manually:
```
kill $(ps aux | grep '[d]river' | awk '{print $2}')
```

**Comment by AlasdairGray** [comment]
This was part of the service that is no longer used #93
