### ISSUE TITLE
Secure connection not working

### ISSUE THREAD

**Issue by AlasdairGray** [HW-SWeL/BMUSE#46]
Chrome is now automatically trying to connect to https://https://lxbisel.macs.hw.ac.uk:8080/scraper, i.e. it converts http to https, which results in the following error.

> This site can’t provide a secure connectionlxbisel.macs.hw.ac.uk sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

On Firefox I was able to access http://https://lxbisel.macs.hw.ac.uk:8080/scraper. The service still works with curl `curl -X GET "http://lxbisel.macs.hw.ac.uk:8080/scraper/getRDF?url=https://aip.fipapatients.org/&output=jsonld" -H "accept: */*"` and the swagger docs still work https://app.swaggerhub.com/apis/kcmcleod/Scraper/

Can we get the service available over https?

**Comment by petrosss** [comment]
I will need to speak to Steve for this.

**Comment by AlasdairGray** [comment]
SWeL server uses https
