### ISSUE TITLE
Bioschemas live deploy page

### ISSUE THREAD

**Issue by AlasdairGray** [HW-SWeL/BMUSE#47]
Should we add an extra column to the Bioschemas live deploy page which would be a call to BMUSE?

**Comment by AlasdairGray** [comment]
It would be nice if we could have some nice UI to display the content. This could be based on John's validation tool.

**Comment by petrosss** [comment]
everything works fine

**Comment by AlasdairGray** [comment]
BMUSE button has been added to Bioschemas website
