### ISSUE TITLE
Bad management of (UTF8?) accented characters

### ISSUE THREAD

**Issue by frmichel** [HW-SWeL/BMUSE#51]
Hey guys, 
I'm giving a try to BMUSE to scrap the Taxon annotation on the pages of the Museum of Natural History of Paris.
On this page: https://inpn.mnhn.fr/espece/cd_nom/60878, the result triples transform accentuated characters like 'à' or 'é' into '?'. 
Example:

`<https://inpn.mnhn.fr/espece/cd_nom/60878> <http://purl.org/dc/terms/title> "Delphinus delphis Linnaeus, 1758 - Dauphin commun, Dauphin commun ? bec court, Dauphin commun ? bec long - Pr?sentation"  .
`

This is usually related to UTF-8 characters not managed correctly. Have you noticed that already? 

Franck.

**Comment by AlasdairGray** [comment]
Thanks @frmichel for reporting this issue. It explains what I had spotted with a sample crawl we had done over the pages as well. We were focusing on other issues so did not look into the problem.

**Comment by frmichel** [comment]
Ok cool, thx, I'll follow on that one.

**Comment by frmichel** [comment]
Hey guys, I've found out the problem: I'm running on a Windows system that default to Cp1252 charset. But on a Linux platform, that works fine.

It is possible to force the default charset to UTF-8 at JVM startup with `-Dfile.encoding=UTF-8`. That fixes the problem. As simple as that... It actually took me quite some time to figure this out, after making lots of unsuccessful changes in the code itself ;)

I've update the main README on my fork, along with all my other changes. We shall probably discuss those before I submit a pull request.

**Comment by AlasdairGray** [comment]
Thanks for updating us. These property settings are always very frustrating.

**Comment by petrospaps** [comment]
Hi Franck,

I think this can be closed now.

**Comment by frmichel** [comment]
Hi @petrospaps, sure, the info in on the README.
I'm closing it.

Franck.
