### ISSUE TITLE
Test failure when compile/run core

### ISSUE THREAD

**Issue by GloC99** [HW-SWeL/BMUSE#73]
Hi,

I tried to compile/run core using `mvn clean package` from inside the core directory but it failed to build due to multiple org.junit.ComparisonFailure and java.lang.AssertionError, caused by, I believe, the \ characters escaped as the ComparisonFailure error message(shortened) shown below.

> 
> org.junit.ComparisonFailure: expected:<..."identifier":"https:[//identifiers.org/MIR:00000364"...> but was:<..."identifier":"https:[\\/\\/identifiers.org\\/MIR:00000364"...>
> at hwu.elixir.scrape.scraper.ScraperFilteredCoreTest.test_injectId_alreadyGotId(ScraperFilteredCoreTest.java:446)

The full output:
[BMUSEerror.txt](https://github.com/HW-SWeL/BMUSE/files/6148801/BMUSEerror.txt)

What can I do to fix this?

Thank you in advance.

**Comment by petrospaps** [comment]
Hi,

Some of the tests have static markup pages that have changed, so BMUSE fails to build because it does not pass the tests.
Please try: mvn clean package -DskipTests
This should build all packages for you.

Best wishes
Petros

**Comment by GloC99** [comment]
Hi Petros,

Thank you so much. It builds now.

**Comment by AlasdairGray** [comment]
I've pushed a fix onto Master that will ignore the failing tests (f06e621)

**Comment by AlasdairGray** [comment]
I've created a new issue to put a longer term fix for this #74
